<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.21.0" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.30.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Orchitect.Storage.Unit.Tests" />
      <InternalsVisibleTo Include="Orchitect.Storage.Integration.Tests" />
    </ItemGroup>

</Project>
